[package]
name = "vrsdn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rtmp = {path = "src/rtmp"}
rtsp = {path = "src/rtsp"}
tokio = { version = "1.36.0", features = ["full"] }